export const featuredJobs = [
  {
    id: "job1",
    title: "Long Haul Truck Driver",
    company: "Express Logistics",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Nationwide (48 States)",
    salary: "$75,000 - $95,000 per year",
    type: "Full-time",
    posted: "2 days ago",
    urgent: true,
  },
  {
    id: "job2",
    title: "Regional Delivery Driver",
    company: "FastFreight Inc.",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Midwest Region",
    salary: "$65,000 - $80,000 per year",
    type: "Full-time",
    posted: "1 week ago",
  },
  {
    id: "job3",
    title: "Local Delivery Driver",
    company: "Urban Logistics",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Chicago, IL",
    salary: "$55,000 - $70,000 per year",
    type: "Full-time",
    posted: "3 days ago",
  },
];

export const jobListings = [
  ...featuredJobs,
  {
    id: "job4",
    title: "OTR Truck Driver",
    company: "National Transport",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Nationwide",
    salary: "$80,000 - $100,000 per year",
    type: "Full-time",
    posted: "1 day ago",
  },
  {
    id: "job5",
    title: "Refrigerated Truck Driver",
    company: "ColdHaul Logistics",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Southeast Region",
    salary: "$70,000 - $90,000 per year",
    type: "Full-time",
    posted: "5 days ago",
    urgent: true,
  },
  {
    id: "job6",
    title: "Tanker Truck Driver",
    company: "Liquid Transport Co.",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Texas, Louisiana, Oklahoma",
    salary: "$85,000 - $110,000 per year",
    type: "Full-time",
    posted: "1 week ago",
  },
  {
    id: "job7",
    title: "Flatbed Truck Driver",
    company: "Heavy Haulers Inc.",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Midwest & Northeast",
    salary: "$75,000 - $95,000 per year",
    type: "Full-time",
    posted: "2 weeks ago",
  },
  {
    id: "job8",
    title: "Team Truck Driver",
    company: "Express Delivery Partners",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Nationwide",
    salary: "$100,000 - $130,000 per year",
    type: "Full-time",
    posted: "3 days ago",
    urgent: true,
  },
  {
    id: "job9",
    title: "Part-Time Delivery Driver",
    company: "Local Freight Services",
    logo: "https://kzmof4c28tjyljmexmxb.lite.vusercontent.net/placeholder.svg?height=100&width=100",
    location: "Denver, CO",
    salary: "$25 - $30 per hour",
    type: "Part-time",
    posted: "4 days ago",
  },
];
